-- Expand tenant users table to include full profile fields used by signup/profile.

ALTER TABLE users ADD COLUMN IF NOT EXISTS pin_number TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_number TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS whatsapp_with_code TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS country TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS religion TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS age INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS height REAL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS weight REAL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS goal_weight REAL;

ALTER TABLE users ADD COLUMN IF NOT EXISTS follow_up_type TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_duration TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_amount REAL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS currency TEXT;

ALTER TABLE users ADD COLUMN IF NOT EXISTS shoulder_width REAL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS chest_width REAL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS waist_width REAL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS hip_width REAL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS front_photo TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS back_photo TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS side_photo TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS has_inbody BOOLEAN DEFAULT FALSE;

ALTER TABLE users ADD COLUMN IF NOT EXISTS fitness_goal TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS training_level TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS training_days_per_week INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_workout_time TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_program TEXT;

ALTER TABLE users ADD COLUMN IF NOT EXISTS medical_history BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS medical_history_details TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS work_intensity TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS workout_location TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS inbody_document TEXT;

ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_meals INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_carbs TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_proteins TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_legumes TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_vegetables TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_dairy TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_fats TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_fruits TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS has_allergies BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS allergy_details TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS wants_supplements BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS supplement_photo TEXT;

ALTER TABLE users ADD COLUMN IF NOT EXISTS previous_trainer BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_routine TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS exercise_history TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS wake_up_time TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS breakfast_time TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS breakfast_details TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS lunch_time TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS lunch_details TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS dinner_time TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS dinner_details TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS lunch_has_protein BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS work_type TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS work_hours TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS has_kitchen_scale BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS payment_receipt TEXT;

ALTER TABLE users ADD COLUMN IF NOT EXISTS how_found_us TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_coach_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS activity_level TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS nutrition_plan TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS workout_plan TEXT;

ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_picture TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS coach_id INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gym_id INTEGER;

ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_type TEXT DEFAULT '1_month';
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_start_date TIMESTAMP DEFAULT NOW();
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_end_date TIMESTAMP;

ALTER TABLE users ADD COLUMN IF NOT EXISTS is_approved BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS approved_by INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_activity_at TIMESTAMP;
