ALTER TABLE branding_settings
  ADD COLUMN IF NOT EXISTS hero_background_type TEXT NOT NULL DEFAULT 'image',
  ADD COLUMN IF NOT EXISTS hero_background_video_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS stats_courses INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stats_coaches INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stats_users INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stats_workouts_completed INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stats_nutrition_plans INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS stats_meals_logged INTEGER NOT NULL DEFAULT 0;