[build]
builder = "NIXPACKS"
buildCommand = "VITE_BASE_PATH=/ CLIENT_OUT_DIR=dist/public npm ci && npm run build"

[deploy]
startCommand = "NODE_ENV=production npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
