-- Core platform tables for auth + demo login (non-interactive bootstrap fallback).
-- Safe to run multiple times on Railway when drizzle-kit push cannot complete.

CREATE TABLE IF NOT EXISTS public.users (
  id SERIAL PRIMARY KEY,
  username TEXT UNIQUE,
  password TEXT NOT NULL,
  pin_number TEXT,
  first_name TEXT NOT NULL DEFAULT '',
  last_name TEXT NOT NULL DEFAULT '',
  phone_number TEXT,
  whatsapp_with_code TEXT,
  city TEXT,
  country TEXT,
  gender TEXT,
  religion TEXT,
  age INTEGER,
  height REAL,
  weight REAL,
  goal_weight REAL,
  subscription_duration TEXT,
  shoulder_width REAL,
  chest_width REAL,
  waist_width REAL,
  hip_width REAL,
  front_photo TEXT,
  back_photo TEXT,
  side_photo TEXT,
  has_inbody BOOLEAN DEFAULT FALSE,
  fitness_goal TEXT,
  training_level TEXT,
  training_days_per_week INTEGER,
  preferred_workout_time TEXT,
  preferred_program TEXT,
  medical_history BOOLEAN DEFAULT FALSE,
  medical_history_details TEXT,
  work_intensity TEXT,
  workout_location TEXT,
  inbody_document TEXT,
  daily_meals INTEGER,
  preferred_carbs TEXT,
  preferred_proteins TEXT,
  preferred_legumes TEXT,
  preferred_vegetables TEXT,
  preferred_dairy TEXT,
  preferred_fats TEXT,
  preferred_fruits TEXT,
  has_allergies BOOLEAN DEFAULT FALSE,
  allergy_details TEXT,
  wants_supplements BOOLEAN DEFAULT FALSE,
  supplement_photo TEXT,
  previous_trainer BOOLEAN DEFAULT FALSE,
  daily_routine TEXT,
  exercise_history TEXT,
  wake_up_time TEXT,
  breakfast_time TEXT,
  breakfast_details TEXT,
  lunch_time TEXT,
  lunch_details TEXT,
  dinner_time TEXT,
  dinner_details TEXT,
  lunch_has_protein BOOLEAN DEFAULT TRUE,
  work_type TEXT,
  work_hours TEXT,
  has_kitchen_scale BOOLEAN DEFAULT FALSE,
  payment_receipt TEXT,
  how_found_us TEXT,
  preferred_coach_name TEXT,
  activity_level TEXT,
  bio TEXT,
  nutrition_plan TEXT,
  workout_plan TEXT,
  role TEXT NOT NULL DEFAULT 'user',
  profile_picture TEXT,
  coach_id INTEGER,
  gym_id INTEGER,
  subscription_type TEXT DEFAULT '1_month',
  subscription_start_date TIMESTAMP DEFAULT NOW(),
  subscription_end_date TIMESTAMP,
  is_approved BOOLEAN DEFAULT TRUE,
  approved_at TIMESTAMP,
  approved_by INTEGER,
  created_at TIMESTAMP DEFAULT NOW(),
  last_activity_at TIMESTAMP,
  email TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON public.users (email) WHERE email IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.products (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  price REAL NOT NULL,
  image_url TEXT,
  category TEXT NOT NULL,
  rating REAL,
  review_count INTEGER,
  stock INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_logins (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  login_at TIMESTAMP NOT NULL DEFAULT NOW(),
  ip_address TEXT,
  user_agent TEXT
);

CREATE INDEX IF NOT EXISTS user_logins_user_id_idx ON public.user_logins(user_id);
CREATE INDEX IF NOT EXISTS user_logins_login_at_idx ON public.user_logins(login_at);
