ALTER TABLE branding_settings
  ADD COLUMN IF NOT EXISTS logo_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS favicon_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS hero_background_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS hero_title TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS hero_subtitle TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS show_hero_section BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_features_section BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_pricing_section BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_cta_section BOOLEAN NOT NULL DEFAULT TRUE;